let attachments = [
    {
        id: 1,
        coId: 1,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 1,
    },
    {
        id: 2,
        coId: 2,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 2,
    },
    {
        id: 3,
        coId: 3,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 3,
    },
    {
        id: 4,
        coId: 4,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 4,
    },
    {
        id: 5,
        coId: 5,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 5,
    },
    {
        id: 6,
        coId: 6,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 6,
    },
    {
        id: 7,
        coId: 7,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 7,
    },
    {
        id: 8,
        coId: 8,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 8,
    },
    {
        id: 9,
        coId: 9,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 9,
    },
    {
        id: 10,
        coId: 10,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 10,
    },
    {
        id: 11,
        coId: 11,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 11,
    },
    {
        id: 12,
        coId: 12,
        npwp: null,
        suratKeteranganAktif: null,
        referensi: null,
        kop: null,
        rekeningKoran: 12,
    },
]